module.exports = {
  ...require('./argv'),
  ...require('./getResource'),
  ...require('./name'),
  ...require('./opts'),
  ...require('./input'),
  ...require('./output'),
  ...require('./size'),
  ...require('./externalize'),
  ...require('./check'),
  ...require('./prettyJSON'),
  ...require('./array'),
  ...require('./rs'),
  ...require('./typeOf'),
  ...require('./injectBabel'),
  ...require('./template'),
};
